"""
reports_section.py
-------------------
Renders the Reports tab: PDF/CSV export actions and a print-friendly
summary table.
"""

import streamlit as st

from utils.helpers import df_to_csv_bytes


def render_reports_section(roster, patient: dict, timeseries) -> None:
    
    st.markdown('<div class="section-title">📄 Reports & Export</div>',
                unsafe_allow_html=True)

    c1, c2, c3 = st.columns(3)
    with c1:
        pdf_summary = (
            f"WOUND MONITORING CLINICAL REPORT\n"
            f"{'=' * 40}\n"
            f"Patient: {patient['name']}\n"
            f"Case ID: {patient['case_id']}\n"
            f"Age / Gender: {patient['age']} / {patient['gender']}\n"
            f"Diabetes Type: {patient['diabetes_type']}\n"
            f"Attending Doctor: {patient['doctor']}\n"
            f"Current Stage: {patient['stage']}\n"
            f"Status: {patient['status']}\n"
            f"Healing Probability: {patient['healing_probability']}%\n"
            f"Risk Level: {patient['risk_level']}\n"
            f"{'-' * 40}\n"
            f"Generated by CareTrack Wound AI — Research Prototype\n"
        )
        st.download_button(
            "🧾 Generate PDF Report", data=pdf_summary,
            file_name=f"{patient['case_id']}_clinical_report.txt",
            mime="text/plain", use_container_width=True,
        )
    with c2:
        st.download_button(
            "📊 Export CSV (Roster)", data=df_to_csv_bytes(roster),
            file_name="patient_roster_export.csv", mime="text/csv",
            use_container_width=True,
        )
    with c3:
        st.button("🖨️ Print Report", use_container_width=True,
                   help="Use your browser's print dialog (Ctrl/Cmd + P)")

    st.markdown("<div style='height:10px'></div>", unsafe_allow_html=True)
    st.markdown('<div class="info-label">Visit-Level Data (current patient)</div>',
                unsafe_allow_html=True)
    st.dataframe(timeseries, use_container_width=True, hide_index=True)
    
